// ✅ Define expected headers based on type
export const EXPECTED_HEADERS = {
  CREATE_CONTRACT: [
    "ID",
    "CS_ID",
    "CO_ID",
    "SN_CODE",
    "SP_CODE",
    "MSISDN",
    "ACTION",
    "CHARGING_CODE",
    "CHARGING_AMOUNT",
    "CHARGING_FREQUENCY",
    "SERVICE_CONTEXT",
    "PARAMETER_LIST",
    "STATUS",
    "EXPIRY_DATE",
    "FILE_ID",
    "JOB_ID",
    "TEXT_LIST",
    "COMBO_LIST",
    "CHECK_LIST",
    "CURRENCY",
    "SUBSCRIPTION_DATE",
    "BILL_DETAIL",
    "TMCODE",
    "SIM_NUM",
    "STATUS_REASON",
    "CONTRACT_STATUS",
    "TEMPLATE_NAME",
    "ACTION_SETOFFERID",
    "OFFERID",
    "OFFERPROVIDERID",
    "OFFERTYPE",
    "CREATION_DATE",
  ],
  SET_STATUS: [
    "ID",
    "FILE_ID",
    "MSISDN",
    "COID",
    "STATUS",
    "REASON",
    "VALIDFROM",
    "TEMPLATENAME",
    "JOB_ID",
  ],
};

// ✅ Define mapping Excel header -> backend field
export const fieldMapping = {
  ID: "id",
  MSISDN: "msisdn",
  ACTION: "action",
  SIGN_CONTRACT_3G_DATE: "signContractDate",
  TEMPLATE_NAME: "templateName",
  USER_LOGIN: "userLogin",
  FILE_ID: "fileId",
  NOTIFICATION_MSISDN: "notificationMsisdn",
  NOTIFICATION_TEMPLATE: "notificationTemplate",
  JOB_ID: "jobId",
  PROMO: "promo",
  CO_ID: "coId",
};
