import { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import * as XLSX from "xlsx";
import { 
  LuFileUp, 
  LuCheckCircle, 
  LuXCircle, 
  LuAlertTriangle, 
  LuArrowRight, 
  LuRocket, 
  LuSearch, 
  LuTrash2 
} from "react-icons/lu";
import { Modal, Table, Spinner, Badge } from "react-bootstrap";
import { EXPECTED_HEADERS, fieldMapping } from "../config/importConfig";
import "./ImportBatchStyle.css";

const ImportBatch = ({ type, fileId, executionDate }) => {
  const location = useLocation();
  const navigate = useNavigate();
  
  const [autoGeneratedId] = useState(() => {
    const d = new Date();
    const pad = (n) => n.toString().padStart(2, "0");
    return `ManualBatch_${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}_${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`;
  });

  const phoneFromInfoFile = fileId || location.state?.fileId || autoGeneratedId;
  const executionDateFromParent = executionDate || location.state?.executionDate || new Date().toISOString();

  const [file, setFile] = useState(null);
  const [previewData, setPreviewData] = useState([]);
  const [rowStatuses, setRowStatuses] = useState([]);
  const [error, setError] = useState("");
  const [isDragActive, setIsDragActive] = useState(false);
  const [uploading, setUploading] = useState(false);

  const [isFetchingResults, setIsFetchingResults] = useState(false);
  const [resultsData, setResultsData] = useState(null);
  const [showResultsModal, setShowResultsModal] = useState(false);

  const handleClear = () => {
    setFile(null);
    setPreviewData([]);
    setRowStatuses([]);
    setError("");
    setResultsData(null);
  };

  const handleFile = (selectedFile) => {
    setError("");
    if (!selectedFile) return;

    const validTypes = [
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "application/vnd.ms-excel",
    ];
    const maxSize = 2 * 1024 * 1024;

    if (!validTypes.includes(selectedFile.type)) {
      setError("Invalid file type. Please upload an Excel file (.xlsx or .xls).");
      return;
    }
    if (selectedFile.size > maxSize) {
      setError("File is too large. Please upload a file smaller than 2MB.");
      return;
    }

    setFile(selectedFile);

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const data = new Uint8Array(event.target.result);
        const workbook = XLSX.read(data, { type: "array" });

        if (!workbook.SheetNames.length) {
          setError("The Excel file is empty or invalid.");
          return;
        }

        const sheetName = workbook.SheetNames[0];
        const worksheet = workbook.Sheets[sheetName];
        const jsonData = XLSX.utils.sheet_to_json(worksheet, { header: 1 });

        const uploadedHeaders = jsonData[0] || [];
        let requiredHeaders = [];

        switch (type) {
          case "CREATE_CONTRACT":
            requiredHeaders = EXPECTED_HEADERS.CREATE_CONTRACT;
            break;
          case "SET_STATUS":
            requiredHeaders = EXPECTED_HEADERS.SET_STATUS;
            break;
          default:
            requiredHeaders = [];
            break;
        }

        if (requiredHeaders.length > 0) {
          const missingColumns = requiredHeaders.filter(
            (header) => !uploadedHeaders.includes(header),
          );

          if (missingColumns.length > 0) {
            setError(`Missing columns: ${missingColumns.join(", ")}`);
            setPreviewData([]);
            return;
          }
        }

        setPreviewData(jsonData);
        setRowStatuses([]);
      } catch (err) {
        setError("Error reading Excel file. Please check the file format.");
      }
    };
    reader.readAsArrayBuffer(selectedFile);
  };

  const handleFileChange = (e) => {
    const selectedFile = e.target.files[0];
    handleFile(selectedFile);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!file || previewData.length < 2) {
      setError("Please select a valid file with data before uploading.");
      return;
    }

    setUploading(true);
    setError("");
    setRowStatuses([]);

    const headers = previewData[0];
    const rows = previewData.slice(1);
    const parsedPayloads = [];

    for (let i = 0; i < rows.length; i++) {
      const row = rows[i];
      if (!row || row.length === 0) continue;

      const payload = {};
      headers.forEach((header, j) => {
        const apiField = fieldMapping[header] || header;
        payload[apiField] = row[j] !== undefined ? row[j] : "";
      });

      payload.fileId = phoneFromInfoFile;
      parsedPayloads.push(payload);
    }

    const masterPayload = {
      executionDate: executionDateFromParent,
      fileId: phoneFromInfoFile,
      operationType: type,
      data: parsedPayloads
    };

    try {
      const res = await fetch("http://localhost:5000/api/users/upload-batch", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(masterPayload),
      });

      if (res.ok) {
        const successStatuses = parsedPayloads.map((_, i) => ({ row: i + 1, status: "success" }));
        setRowStatuses(successStatuses);
      } else {
        const errData = await res.json();
        setError(`Upload Failed: ${errData.error || errData.message || "Unknown error"}`);
      }
    } catch (err) {
      setError(`Network Error: ${err.message}`);
    }

    setUploading(false);
  };

  const viewResults = async () => {
    if (!phoneFromInfoFile) return;

    setIsFetchingResults(true);
    setError("");

    try {
      const res = await fetch("http://localhost:5000/api/users/resultBatch", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ fileId: phoneFromInfoFile }),
      });

      if (res.ok) {
        const data = await res.json();
        setResultsData(data);
        setShowResultsModal(true);
      } else {
        const errData = await res.json();
        setError(`Fetch Failed: ${errData.error || "Could not retrieve results"}`);
      }
    } catch (err) {
      setError(`Network Error: ${err.message}`);
    } finally {
      setIsFetchingResults(false);
    }
  };

  const successCount = rowStatuses.filter((r) => r.status === "success").length;
  const errorCount = rowStatuses.filter((r) => r.status === "error").length;
  const isAllUploaded = rowStatuses.length > 0 && errorCount === 0;

  return (
    <div className="container py-5">
      <div className="import-card">
        {/* Header Section */}
        <div className="text-center mb-4">
          <h1 className="import-header">
            <LuRocket className="me-2" size={32} /> Batch Import
          </h1>
          <div className="file-info-badge">
            <LuSearch size={16} className="me-2" /> File ID: <strong>{phoneFromInfoFile || "Manual Input"}</strong>
          </div>
        </div>

        {/* Upload Interface */}
        <div className="row g-4 mb-4">
          <div className="col-lg-12">
            <div
              className={`modern-dropzone ${isDragActive ? "active" : ""}`}
              onDragOver={(e) => { e.preventDefault(); setIsDragActive(true); }}
              onDragLeave={() => setIsDragActive(false)}
              onDrop={(e) => {
                e.preventDefault();
                setIsDragActive(false);
                handleFile(e.dataTransfer.files[0]);
              }}
              onClick={() => document.getElementById("file-upload-input").click()}
            >
              <LuFileUp className="upload-icon" size={56} />
              <h4 className="fw-bold">Upload Excel Data</h4>
              <p className="text-muted">Drag & Drop your .xlsx or .xls file here, or click to browse</p>
              <input
                id="file-upload-input"
                type="file"
                accept=".xlsx, .xls"
                onChange={handleFileChange}
                className="d-none"
              />
              {file && (
                <div className="mt-3 text-danger fw-bold">
                  📁 Selected: {file.name}
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Actions & Summary */}
        <div className="d-flex flex-wrap justify-content-between align-items-center mb-4">
          <div className="d-flex gap-3 mt-2">
            <button
              onClick={handleSubmit}
              className="btn btn-ooredoo d-flex align-items-center gap-2"
              disabled={uploading || !file || previewData.length < 2}
            >
              {uploading ? (
                <>
                  <Spinner animation="border" size="sm" /> <span>Uploading...</span>
                </>
              ) : (
                <>
                  <LuFileUp size={18} /> Upload Batch
                </>
              )}
            </button>
            <button
              className="btn btn-ooredoo-outline d-flex align-items-center gap-2"
              onClick={handleClear}
              disabled={uploading || !file}
            >
              <LuTrash2 size={18} /> Clear Data
            </button>
          </div>

          <div className="d-flex gap-4 align-items-center mt-2">
            {rowStatuses.length > 0 && (
              <div className="d-flex gap-3">
                <div className="d-flex align-items-center gap-2">
                  <LuCheckCircle className="text-success" />
                  <span className="fw-bold">Success: {successCount}</span>
                </div>
                {errorCount > 0 && (
                  <div className="d-flex align-items-center gap-2">
                    <LuXCircle className="text-danger" />
                    <span className="fw-bold">Errors: {errorCount}</span>
                  </div>
                )}
              </div>
            )}

            {isAllUploaded && (
              <button
                className="btn btn-ooredoo-success d-flex align-items-center gap-2"
                onClick={viewResults}
                disabled={isFetchingResults}
              >
                {isFetchingResults ? (
                  <Spinner animation="border" size="sm" />
                ) : (
                  <>
                    View Activation Results <LuArrowRight size={18} />
                  </>
                )}
              </button>
            )}
          </div>
        </div>

        {error && (
          <div className="alert alert-danger d-flex align-items-center gap-3">
            <LuAlertTriangle size={20} />
            <div>{error}</div>
          </div>
        )}

        {/* Data Preview */}
        {previewData.length > 0 && (
          <div className="mt-5">
            <div className="d-flex align-items-center gap-2 mb-3">
              <div style={{width: 4, height: 24, backgroundColor: '#ed1c24', borderRadius: 2}}></div>
              <h5 className="mb-0 fw-bold">Raw Data Preview</h5>
            </div>
            <div className="table-responsive shadow-sm modern-table">
              <table className="table mb-0">
                <thead>
                  <tr>
                    {previewData[0].map((header, idx) => (
                      <th key={idx}>
                        {header}
                        <div className="text-muted fw-normal" style={{fontSize: '0.7rem'}}>
                          {fieldMapping[header] || '~'}
                        </div>
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {previewData.slice(1, 6).map((row, i) => (
                    <tr key={i}>
                      {previewData[0].map((_, j) => (
                        <td key={j} className={!row[j] ? "bg-light" : ""}>
                          {row[j] !== undefined ? String(row[j]) : "-"}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
              {previewData.length > 6 && (
                <div className="p-2 text-center text-muted small border-top">
                  ... and {previewData.length - 6} more rows
                </div>
              )}
            </div>
          </div>
        )}
      </div>

      {/* Activation Results Modal */}
      <Modal show={showResultsModal} onHide={() => setShowResultsModal(false)} size="xl" centered>
        <Modal.Header closeButton style={{ background: 'var(--header-gradient)', color: 'white' }}>
          <Modal.Title className="fw-bold">Activation Results (Oracle ESB_LOG)</Modal.Title>
        </Modal.Header>
        <Modal.Body className="p-0">
          <div className="p-4 bg-light border-bottom">
            <div className="row g-3">
              <div className="col-md-3">
                <label className="text-muted small">File ID</label>
                <div className="fw-bold">{resultsData?.batchInfo?.fileId}</div>
              </div>
              <div className="col-md-3">
                <label className="text-muted small">Operation</label>
                <div className="fw-bold"><Badge bg="danger">{resultsData?.batchInfo?.operationType}</Badge></div>
              </div>
              <div className="col-md-3">
                <label className="text-muted small">Batch Status</label>
                <div className="fw-bold"><Badge bg="dark">{resultsData?.batchInfo?.etat}</Badge></div>
              </div>
              <div className="col-md-3">
                <label className="text-muted small">Result Count</label>
                <div className="fw-bold text-success">{resultsData?.oracleResultsCount} recorded</div>
              </div>
            </div>
          </div>
          
          <div className="table-responsive" style={{ maxHeight: '60vh' }}>
            <Table striped borderless hover className="mb-0 align-middle">
              <thead>
                <tr>
                  <th className="ps-4">MSISDN</th>
                  <th>Transaction ID</th>
                  <th>Status</th>
                  <th>Message</th>
                  <th>Step</th>
                  <th>Date</th>
                </tr>
              </thead>
              <tbody>
                {resultsData?.transactionResults?.length > 0 ? (
                  resultsData.transactionResults.map((r, i) => (
                    <tr key={i}>
                      <td className="ps-4 fw-bold">{r.msisdn}</td>
                      <td className="small text-muted">{r.TRANSACTION_ID || r.transactionId}</td>
                      <td>
                        <Badge 
                          bg={r.STATUS === 'SUCCESS' || r.STATUS === 'FINISHED' ? 'success' : r.STATUS === 'PENDING' ? 'warning' : 'danger'}
                        >
                          {r.STATUS || 'UNKNOWN'}
                        </Badge>
                      </td>
                      <td className="small">{r.PROCESS_ADDITION_MSG || r.MAIN_INFO || '-'}</td>
                      <td><Badge bg="light" text="dark">{r.TRACE_IN_STEP || '-'}</Badge></td>
                      <td className="small text-muted">{r.STATUS_DATE || r.CREATION_DATE || '-'}</td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan="6" className="text-center py-5">
                      <LuSearch size={32} className="text-muted mb-3 d-block mx-auto" />
                      <h5 className="text-muted">No results found in ESB_LOG.</h5>
                    </td>
                  </tr>
                )}
              </tbody>
            </Table>
          </div>
        </Modal.Body>
        <Modal.Footer>
          <button className="btn btn-secondary px-4" onClick={() => setShowResultsModal(false)}>Close</button>
          <button className="btn btn-ooredoo px-4" onClick={() => window.print()}>Export Results</button>
        </Modal.Footer>
      </Modal>
    </div>
  );
};

export default ImportBatch;
